### ISSUE TITLE
English and Spanish combination

### ISSUE THREAD

**Issue by Danilux** [Jason3S/vscode-cspell-dict-extensions#1]
Hi, just installed, added "cSpell.language": "es, en", I want to have english and spanish suggestions, but I get on the left a lightbulb that gives a spanish word suggestions list, and if I press ctrl+space I get an english list of word suggestions, is this how it's supposed to work? thanks

**Comment by Jason3S** [comment]
It should give you both.

A few things can be happening:
- `cSpell.language` exists in the workspace settings.
- `language` exists in a cspell.json file in the workspace root or `.vscode`.
- (unlikely) the English words are closer in edit distance than the Spanish words.

Things to try:
- `F1` `Enable Spanish Workspace`
- Edit the `.vscode/settings.json` file
- Edit `.vscode/cspell.json` file if it exists.

If none of these work, please send me some of the words that are not giving you a good suggestion and I will try them on my side.

**Comment by Jason3S** [comment]
Hello @Danilux,

I saw something like this the other day. It seems that VS Code keeps a cache of suggestions. So, when you first turn on a dictionary, it might not give suggestions for the dictionary that was just enabled.

Good news is that it will fix itself once the cache expires. Restarting VS Code, or just waiting for for some time seems to do the trick.

I don't have any other information than that.

I'll close this issue for now. But if it still happens to you, please re-open or create a new issue and refer to this one.
