### ISSUE TITLE
Enabling German disables English

### ISSUE THREAD

**Issue by hho** [Jason3S/vscode-cspell-dict-extensions#13]
When first enabling German spellcheck, it created the preferences entry as `"cSpell.language": ",de"`, effectively disabling English.

It would be better, if it created the combination of both languages (like the example unter "Manual Settings" in the [Overview](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-german)).

**Comment by Jason3S** [comment]
Thank you. 
It was/is designed to use both languages. Something must have gone wrong.
I'll take a look.

In the mean time,
`F1 Show Spell Checker Configuration Info` will bring up a dialog that allows you to turn on/off languages.

![image](https://user-images.githubusercontent.com/3740137/42313502-3a7c7bca-8043-11e8-83b8-dba99d92f541.png)

**Comment by hho** [comment]
Thank you so much! I just used the manual way from the (awesome) docs, but the UI is even nicer.
