### ISSUE TITLE
Turkish Add-On Dictionary extension is not published

### ISSUE THREAD

**Issue by umutozel** [Jason3S/vscode-cspell-dict-extensions#19]
Can not find Turkish Add-On Dictionary on marketplace but I can see the code on github. Any plan on publishing it? Or is there any work waiting to be finished (would be glad to help) ?

**Comment by ofenerci** [comment]
I would like to see the same enhancement.

**Comment by Jason3S** [comment]
Thank you, I'll publish it.

**Comment by Jason3S** [comment]
Done: [Turkish - Code Spell Checker - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-turkish)
