### ISSUE TITLE
Portuguese dictionary

### ISSUE THREAD

**Issue by porfirioribeiro** [Jason3S/vscode-cspell-dict-extensions#5]
Would it be possible to add Portuguese (pt_PT) language to this plug-in?

**Comment by Jason3S** [comment]
If you would like to help, the instructions on how to generate the extension are in the README.

Just do a pull request, and I will publish it after I get the chance to verify it is working.

**Comment by Jason3S** [comment]
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-portuguese
