### ISSUE TITLE
Be careful with the updates!!!

### ISSUE THREAD

**Issue by ergcode** [Jason3S/vscode-cspell-dict-extensions#7]
![2017-12-17_194030](https://user-images.githubusercontent.com/23062770/34081741-0103a508-e363-11e7-850e-7cd35db2988f.png)
WTF???

50% CPU,
1 Gb RAM...

**Comment by Jason3S** [comment]
Did you try restarting VS Code? Sometimes when extensions or VS Code gets
updated. Old version are stuck in limbo.

**Comment by ergcode** [comment]
I deleted the extension and dependency, will reinstall tomorrow.

**Comment by Jason3S** [comment]
Please let me know how it goes.

**Comment by ergcode** [comment]
No problem.

**Comment by ergcode** [comment]
![2017-12-17_201510](https://user-images.githubusercontent.com/23062770/34081958-0131710a-e367-11e7-9450-9edc7ca9519e.png)
The reinstallation solved the problem. 

Another remark. The extension takes up 273 MB of HDD after installation. In Sublime Text 3 Russian and English dictionaries have is 15 MB HDD.

**Comment by Jason3S** [comment]
I’m looking into that. It seems like the packaging utility is pulling in
too much stuff.

**Comment by Jason3S** [comment]
The size should be around 5 MB

**Comment by Jason3S** [comment]
I found the issue with the size.

The VS Code test running got packaged with the extension.

**Comment by Jason3S** [comment]
This should be fixed. Please open a new issue an refer to this one if it is not.

**Comment by ergcode** [comment]
Thank you for your efforts! 
I'll check tomorrow and give an answer.
